'use strict';
const API='https://businesscontracts.aproposgroupllc.com/api/opportunity-workspace';
const PACKAGE_API='https://businesscontracts.aproposgroupllc.com/api/opportunity-package';
const BRIEF_API='https://businesscontracts.aproposgroupllc.com/api/contract-brief';
const $=id=>document.getElementById(id);
const token=new URLSearchParams(location.search).get('t')||'';
let workspace=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=(value,withTime=false)=>{if(!value)return'Not specified';const d=new Date(value);if(Number.isNaN(d.getTime()))return String(value);return new Intl.DateTimeFormat('en-US',{dateStyle:'long',...(withTime?{timeStyle:'short'}:{})}).format(d)};
const fmtBytes=value=>{const n=Number(value||0);if(!n)return'—';if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`};
const locationText=o=>[o.place_of_performance_city,o.place_of_performance_county,o.place_of_performance_state].filter(Boolean).join(', ')||'See solicitation package';

async function api(method='GET',body){const url=`${API}?t=${encodeURIComponent(token)}`;const response=await fetch(url,{method,cache:'no-store',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
async function record(action){try{await api('POST',{action})}catch(error){console.warn('Opportunity activity was not recorded:',error.message)}}
function showError(message){$('loading').classList.add('hidden');$('workspace').classList.add('hidden');$('errorMessage').textContent=message;$('errorState').classList.remove('hidden')}
function renderDocuments(documents){if(!documents.length){$('documents').innerHTML='<p>No stored package documents are currently available.</p>';return}$('documents').innerHTML=documents.map(doc=>{const tag=doc.is_addendum?'Addendum':doc.is_amendment?'Amendment':doc.document_type||'Contract document';const tagClass=doc.is_addendum||doc.is_amendment?'doc-tag addendum':'doc-tag';return`<article class="document-row"><div class="document-name"><strong>${esc(doc.original_filename||'Contract document')}</strong><small>${esc(doc.version_label||'Current version')} · Retrieved ${esc(fmtDate(doc.retrieved_at))}</small></div><span class="${tagClass}">${esc(tag)}</span><span class="doc-meta">${esc(fmtBytes(doc.byte_size))}</span>${doc.download_url?`<a class="download-link" href="${esc(doc.download_url)}" target="_blank" rel="noopener" data-download>Download</a>`:'<span class="doc-meta">Unavailable</span>'}</article>`}).join('');document.querySelectorAll('[data-download]').forEach(link=>link.addEventListener('click',()=>record('package_downloaded')))}
function render(data){workspace=data;const o=data.opportunity||{},a=data.access||{},docs=data.documents||[];$('title').textContent=o.title||'Contract opportunity';$('agency').textContent=[o.issuing_organization,o.issuing_department].filter(Boolean).join(' · ');$('clientBusiness').textContent=a.client_business_name||'Your business';$('deadline').textContent=fmtDate(o.response_deadline);$('deadlineTime').textContent=o.response_deadline?new Date(o.response_deadline).toLocaleTimeString([],{hour:'numeric',minute:'2-digit',timeZoneName:'short'}):'';$('statusBadge').textContent=String(o.status||'Open').toUpperCase();$('description').textContent=o.description||'Review the complete solicitation package for the official scope, requirements and submission instructions.';$('solicitation').textContent=o.solicitation_number||o.pdas_record_id||'Not specified';$('issuingAgency').textContent=[o.issuing_organization,o.issuing_department].filter(Boolean).join(' — ')||'Not specified';$('procurementType').textContent=o.procurement_type||'See solicitation';$('location').textContent=locationText(o);$('questionDeadline').textContent=fmtDate(o.question_deadline,true);$('prebid').textContent=fmtDate(o.prebid_datetime,true);$('officialSource').href=o.official_source_url||o.source_url||'#';$('packageSummary').textContent=`${docs.length} verified file${docs.length===1?'':'s'} available · Package completed ${fmtDate(o.package_completed_at)}.`;$('packageBadge').textContent=o.package_status==='PACKAGE_COMPLETE'?'Package Verified':'Package Review Required';renderDocuments(docs);$('briefDownload').classList.remove('disabled');$('briefDownload').removeAttribute('aria-disabled');$('briefDownload').textContent='Download APROPOS Contract Brief';$('briefDownload').href=`${BRIEF_API}?t=${encodeURIComponent(token)}`;$('briefDownload').onclick=()=>record('contract_brief_downloaded');$('downloadPackage').onclick=()=>{record('package_downloaded');location.href=`${PACKAGE_API}?t=${encodeURIComponent(token)}`};$('purchaseAnalyzeFit').onclick=async()=>{await record('analyze_fit_requested');const params=new URLSearchParams({product:'analyze-fit',opportunity_id:o.id,workspace_return:`https://aproposgroupllc.com/opportunity?t=${token}`});location.href=`${data.purchase_url}${data.purchase_url.includes('?')?'&':'?'}${params}`};$('loading').classList.add('hidden');$('workspace').classList.remove('hidden')}
async function init(){if(!token||token.length<32){showError('This opportunity link is incomplete. Use the secure link supplied by APROPOS Group LLC.');return}try{render(await api())}catch(error){showError(error.message)}}
init();
